target-version = "py37"

[lint]
extend-select = [
    "A",
    "C4",
    "EXE",
    "ISC",
    "LOG",
    "G",
    "PIE",
    "PYI",
    "RET",
    "SIM",
    "FLY",
    "PERF",
    "E",
    "W",
    "PGH",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "UP",
    "FURB",
    "RUF",
    "TRY",
]
ignore = [
    "ISC001",
    "ISC002",
    "SIM102",
    "SIM108",
    "SIM115",
    "SIM118",
    "E501",
    "PLC0415",
    "PLR091",
    "PLR2004",
    "PLW0602",
    "PLW0603",
    "PLW1510",
    "RUF002",
    "RUF012",
]
